name: Test

on:
  push:
  workflow_dispatch:

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04]
        version: ["3.0", "3.1", "3.2"]
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          ruby-version: ${{ matrix.version }}

      - run: |
          ruby --version | grep '^ruby ${{ matrix.version }}'
          dpkg -l 'ruby' | grep 'ii'
          dpkg -l 'ruby${{ matrix.version }}' | grep 'ii'
  patch:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04]
        version: ["3.0.5", "3.1.3", "3.2.1"]
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          ruby-version: ${{ matrix.version }}

      - run: |
          ruby --version | grep '^ruby ${{ matrix.version }}'

  ruby-version-file:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04]
        version: ["3.0", "3.1", "3.2"]
        testcase: [with_lockfile]
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - run: echo '${{ matrix.version }}' > .ruby-version

      - uses: ./

      - run: |
          ruby --version | grep '^ruby ${{ matrix.version }}'
          dpkg -l 'ruby' | grep 'ii'
          dpkg -l 'ruby${{ matrix.version }}' | grep 'ii'

  bundle-cache:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04]
        version: ["3.0", "3.1", "3.2"]
        testcase: [with_lockfile]
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: __tests__/${{ matrix.testcase }}/Gemfile
