name: Test

on:
  push:
  workflow_dispatch:

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        version: ["3.0", "3.1", "3.2", "3.3", "3.4"]
        exclude:
          - runner: ubuntu-20.04
            version: "3.4"
          - runner: ubuntu-24.04
            version: "3.0"
          - runner: ubuntu-24.04
            version: "3.1"
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          ruby-version: ${{ matrix.version }}

      - run: |
          ruby --version | grep '^ruby ${{ matrix.version }}'
          dpkg -l 'ruby' | grep 'ii' | grep '${{ matrix.version}}'
          dpkg -l 'ruby${{ matrix.version }}' | grep 'ii'
          dpkg -l 'libruby${{ matrix.version}}' | grep 'ii'
        shell: bash

  patch:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        version: ["3.0.5", "3.1.3", "3.2.6", "3.3.1", "3.4.1"]
        exclude:
          - runner: ubuntu-20.04
            version: "3.4.1"
          - runner: ubuntu-24.04
            version: "3.0.5"
          - runner: ubuntu-24.04
            version: "3.1.3"
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          ruby-version: ${{ matrix.version }}

      - run: |
          ruby --version | grep '^ruby ${{ matrix.version }}'
        shell: bash

  ruby-version-file:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        version: ["3.0", "3.1", "3.2", "3.3", "3.4"]
        testcase: [with_lockfile]
        exclude:
          - runner: ubuntu-20.04
            version: "3.4"
            testcase: "with_lockfile"
          - runner: ubuntu-24.04
            version: "3.0"
            testcase: "with_lockfile"
          - runner: ubuntu-24.04
            version: "3.1"
            testcase: "with_lockfile"
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - run: echo '${{ matrix.version }}' > .ruby-version

      - uses: ./

      - run: |
          ruby --version | grep '^ruby ${{ matrix.version }}'
          dpkg -l 'ruby' | grep 'ii'
          dpkg -l 'ruby${{ matrix.version }}' | grep 'ii'
        shell: bash

  bundle-cache:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        version: ["3.0", "3.1", "3.2", "3.3", "3.4"]
        testcase: [with_lockfile]
        exclude:
          - runner: ubuntu-20.04
            version: "3.4"
            testcase: "with_lockfile"
          - runner: ubuntu-24.04
            version: "3.0"
            testcase: "with_lockfile"
          - runner: ubuntu-24.04
            version: "3.1"
            testcase: "with_lockfile"
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: __tests__/${{ matrix.testcase }}/Gemfile
